#!/bin/bash
# Nek5000 build config file
# (c) 2008,2009,2010 UCHICAGO ARGONNE, LLC

# source path 

#SOURCE_ROOT="/home/marco/nek1093_dong/trunk/nek"
SOURCE_ROOT="../Nek1093_dong/trunk/nek"
SOURCE_ROOT2="$SOURCE_ROOT/cmt"


# Fortran compiler
# F77="mpif90 -std=legacy" 
F77="mpif90 -std=legacy" 
# F77="mpif77 -std=legacy"

#C compiler
CC="mpicc"

# pre-processor symbol list 
# (set PPLIST=? to get a list of available symbols)
PPLIST="MPIIO" 

# plug-in list
# PLUGIN_LIST=""


# OPTIONAL SETTINGS
# -----------------

# enable MPI (default true)
#IFMPI="false"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR="foo.o"

# linking flags
#USR_LFLAGS="-L/usr/lib -lfoo"

# generic compiler flags
G="-I./inc_src -mcmodel=large"
# G="-g"

# optimization flags
#OPT_FLAGS_STD=""
#OPT_FLAGS_MAG=""

# enable AMG coarse grid solver (default XXT)
#IFAMG="true"
#IFAMG_DUMP="true"

# CVODE path
#CVODE_DIR=$HOME/cvode/lib
 
# MOAB/iMESH path
#MOAB_DIR="$HOME/moab"


###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$2"
  echo "change source code directory to: ", $SOURCE_ROOT
fi
# do some checks and create makefile
source $SOURCE_ROOT/makenek.inc
# compile
make -j4 -f makefile 2>&1 | tee compiler.out
exit 0
